

obj-$(CONFIG_CXX_RUNTIME_TEST) += test_exception.o

obj-$(CONFIG_CXX_RUNTIME_TEST) += test_dynamic_cast.o

obj-$(CONFIG_CXX_RUNTIME_TEST) += test_classes.o

#obj-y += test_exception.o

#obj-y += test_dynamic_cast.o

#obj-y += test_classes.o

test_classes-objs := test_classes_imp.o

test_exception-objs := test_exception_imp.o

test_dynamic_cast-objs := test_dynamic_cast_imp.o

